---
version: 2
updates:

  # Maintain dependencies for Python
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: wednesday
      time: 18:00
    labels:
      - dependencies
      - triage
    commit-message:
      prefix: build
      include: scope
    rebase-strategy: auto
    versioning-strategy: increase-if-necessary

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: wednesday
      time: 18:00
    labels:
      - dependencies
      - triage
    rebase-strategy: auto
    commit-message:
      prefix: ci
      include: scope
